### ISSUE TITLE
Crash when running on windows

### ISSUE THREAD

**Issue by pchiusano** [slideshow-s9/slideshow-models#1]
C:\stuff>gem install slideshow
... installs successfully
C:\stuff>echo hi > intro.textile
C:\stuff>slideshow intro
Slide Show (S9) Version: 0.8 on Ruby 1.8.6 (2008-08-11) [i386-mswin32]
C:/programs/Ruby/lib/ruby/gems/1.8/gems/slideshow-0.8/lib/slideshow/gen.rb:87:in `win32_cache_dir': undefined method`+' for nil:NilClass (NoMethodError)
        from C:/programs/Ruby/lib/ruby/gems/1.8/gems/slideshow-0.8/lib/slideshow/gen.rb:83:in `cache_dir'
        from C:/programs/Ruby/lib/ruby/gems/1.8/gems/slideshow-0.8/lib/slideshow/gen.rb:102:in`config_dir'
        from C:/programs/Ruby/lib/ruby/gems/1.8/gems/slideshow-0.8/lib/slideshow/gen.rb:565:in `load_plugins'
        from C:/programs/Ruby/lib/ruby/gems/1.8/gems/slideshow-0.8/lib/slideshow/gen.rb:663:in`run'
        from C:/programs/Ruby/lib/ruby/gems/1.8/gems/slideshow-0.8/lib/slideshow.rb:37:in `main'
        from C:/programs/Ruby/lib/ruby/gems/1.8/gems/slideshow-0.8/bin/slideshow:4
        from C:/programs/Ruby/bin/slideshow:19:in`load'
        from C:/programs/Ruby/bin/slideshow:19

I don't know ruby at all, but the offending line is: unless File.exists?(home = ENV['HOMEDRIVE'] + ENV['HOMEPATH']). I don't have a HOMEDRIVE environment variable, so I'm guessing ENV['HOMEDRIVE'] returns nil and attempting to concatenate that bombs. This is on windows. Perhaps the logic should be something like - if either homedrive or homepath is null, or if homedrive + homepath refers to a nonexistent directory, then print the message and return the current directory, otherwise, do the other branch.

If it's a requirement that homedrive and homepath exist, that should probably be documented prominently in the quickstart guide.

**Comment by geraldb** [comment]
Added check for env variables. If they don't exist you will get this message: No HOMEDRIVE or HOMEPATH environment variable.  Set one to save a local cache of stylesheets for syntax highlighting and more.
