### ISSUE TITLE
create lib plugins (I don't know whether it is an issue or not)

### ISSUE THREAD

**Issue by halida** [slideshow-s9/slideshow-models#10]
hello, I'm following the tutorial:

http://slideshow.rubyforge.org/plugins.html

and create a markdown_helper.rb file in .lib/ of my slideshow project.

after I run slideshow, it tells me:

```
Loading plugins in 'lib/markdown_helper.rb'...
** error: failed loading plugins in 'lib/markdown_helper.rb': cannot load such file -- lib/markdown_helper.rb
```

so I change this:

https://github.com/geraldb/slideshow/blob/master/lib/slideshow/gen.rb#L423

to:

``` ruby
require( "./"+plugin )
```

and everything OK.

Is it a bug, or I create something wrong?

**Comment by geraldb** [comment]
Thanks for reporting the issue. In the latest update I added the plugins command, that is, issue

```
slideshow plugins
```

to checkup on the loading path for plugins. Cheers.

**Comment by geraldb** [comment]
Thanks. It's fixed now. Found out the cause. Starting in Ruby 1.9.2+ the current folder, that is, `./` is no longer on the load path. All plugins starting w/ slideshow 2.0.1 get loaded with the full path and, thus, work on any Ruby version. Cheers.
