### ISSUE TITLE
Issue when running slideshow -q

### ISSUE THREAD

**Issue by cmoulliard** [slideshow-s9/slideshow-models#11]
Hi,

I get the following error when running slideshow -q :

Progresss-MacBook-Pro:Temp chmoulli$ slideshow -q
/Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/slideshow-1.1.0/lib/slideshow.rb:1: warning: variable $KCODE is no longer effective; ignored
/Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/slideshow-1.1.0/lib/slideshow/runner.rb:161:in `run': invalid option: -q (OptionParser::InvalidOption)
    from /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/slideshow-1.1.0/lib/slideshow.rb:99:in`main'
    from /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/slideshow-1.1.0/bin/slideshow:5:in `<top (required)>'
    from /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/bin/slideshow:19:in`load'
    from /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/bin/slideshow:19:in `<main>'
    from /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in`eval'
    from /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'

Regards,

Charles

**Comment by geraldb** [comment]
Hello Charles,
  Thanks for reporting. The -q/--quick switch is a new option currently in beta (that is, only available with --pre installs) and some details are currently changing before the release early next week. Please, update/install the slideshow gem on Monday next week and everything should be working than. Cheers.
