### ISSUE TITLE
Documentation request: Templates

### ISSUE THREAD

**Issue by Atalanta** [slideshow-s9/slideshow-models#13]
Hello,

I'm trying to create a template pack.  But there seems to be no compleye documentation on this at all, and that little which i can find references a generate command that doesn't exist any more.

I am trying to reverse engineer an existing theme, but without much joy.

Please help?

S.

**Comment by geraldb** [comment]
The easiest way to create a new template pack is cloning or looking at an existion one. You will find 10+ template packs at the slideshow repo site -> https://github.com/slideshow-s9        For questions you're inivited to post them here or better and prefered to the mailing list -> http://groups.google.com/group/webslideshow        A small template reference is online -> http://slideshow-s9.github.io/template.html  Cheers.
