### ISSUE TITLE
google-html5-slides

### ISSUE THREAD

**Issue by cfr** [slideshow-s9/slideshow-models#5]
$ slideshow -f http://github.com/geraldb/slideshow-google-html5-slides/raw/master
Invalid gemspec in [/usr/lib/ruby/gems/1.9.1/specifications/ncursesw-1.2.4.3.gemspec]: invalid date format in specification: "2010-11-9 13:45:50 -08:00"
/usr/lib/ruby/gems/1.9.1/gems/slideshow-0.9.9/lib/slideshow.rb:1: warning: variable $KCODE is no longer effective; ignored
/usr/lib/ruby/gems/1.9.1/gems/RedCloth-4.2.8/lib/redcloth.rb:10: Use RbConfig instead of obsolete and deprecated Config.
Slide Show (S9) Version: 0.9.9 on Ruby 1.9.3 (2011-10-30) [i686-linux]
Fetching template package 'master'
  : from 'http://github.com:80/geraldb/slideshow-google-html5-slides/raw'
  : saving to '/root/.slideshow/templates/master'
  Downloading manifest 'master'...
  Downloading template '_.kpf'...
*_\* error: 404 Not Found
Done.

**Comment by geraldb** [comment]
Hello Stan,

   If you fetch a template pack you need to speficify the manifest (not only the path), that is, use:

  $ slideshow -f http://github.com/geraldb/slideshow-google-html5-slides/raw/master/g5.txt

  Cheers.
