### ISSUE TITLE
Missing img tags when placed inside a {% right %} block

### ISSUE THREAD

**Issue by raghur** [slideshow-s9/slideshow-models#8]
# Steps:
1. Install either rdiscount or bluecloth
2. create a slide like so:
   
   ```
     {% left %}
     ![](images/some.png)
     {% end %}
   ```
3. Generated markup
   
   ```
      <td>![](images/some.png)</td>
   ```
4. Expected result:
   
   ```
      <td><img src="images/some.png"/></td>
   ```

The same markdown with the default Kramdown generates proper markup. Also, moving the inline image out of the `{%left %}` block results in proper image tag generation with rdiscount/bluecloth - so this seems to be something that's wrong with slideshow.

**Comment by geraldb** [comment]
Thanks for reporting the issue. Standard Markdown requires empty lines around blocks. Kramdown might be more tolerant. To make sure it works with all markdown libraries use empty lines before and after blocks e.g. 

```
{% left %}

![](images/some.png)

{% end %}
```

I know. Doesn't look that nice with some extra lines. I will try to find some workaround in future updates. Cheers.
